language: scala
sudo: false

scala:
  - 2.12.8

jdk:
  - openjdk8

before_install:
  - export PATH=${PATH}:./vendor/bundle

stages:
- name: docs
- name: test

jobs:
  include:
    - &docs
      stage: docs
      name: "Docs"
      script: sbt tut
    - &lint
      stage: test
      name: "Lint"
      script: sbt ++$TRAVIS_SCALA_VERSION scalafmtCheck test:scalafmtCheck scalafmtSbtCheck
    - &test
      stage: test
      name: "Test"
      script: sbt ++$TRAVIS_SCALA_VERSION test:run package packageSrc publishLocal
